version: '2.1'
services:
    airflow:
#        image: apache/airflow:1.10.11
        build:
            context: .
#            args:
#                - DOCKER_UID=${DOCKER_UID-1000}
            dockerfile: Dockerfile
        restart: always
        environment:
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
            - AIRFLOW__CORE__FERNET_KEY=KPr56n1SCB9uoco1cjT0Nyr-dKopjaRsNK0K_bBYpZQ=
            - AIRFLOW__CORE__EXECUTOR=LocalExecutor
            - AIRFLOW__CORE__DEFAULT_TIMEZONE=system
            - AIRFLOW__CORE__LOAD_EXAMPLES=False
            - AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS=False
            - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
            - AIRFLOW__SCHEDULER__CATCHUP_BY_DEFAULT=False

            - AIRFLOW__CORE__REMOTE_LOGGING=True
            - AIRFLOW__CORE__REMOTE_BASE_LOG_FOLDER=s3://dbc-ae07f79c-e24f-random-bucket/airflow-logs
            - AIRFLOW__CORE__REMOTE_LOG_CONN_ID=neil-aws-s3-account
        volumes:
            - ./dags:/opt/airflow/dags:z
            - ./plugins:/opt/airflow/plugins:z
            - ./volumes/airflow_data_dump:/opt/airflow/data_dump:z
            - ./volumes/airflow_logs:/opt/airflow/logs:z
